### ISSUE TITLE
Support segment group

### ISSUE THREAD

**Issue by ankitnayan** [PostHog/posthog-segment#11]
We have been using segment as the primary source of data collection and use their client libs to create events and use PostHog as a source in segment. I want to run group analytics on property `company_domain` which would need to enable translation from segment's group to posthog's group.

**Comment by ankitnayan** [comment]
I see `Event not supported` at https://github.com/PostHog/posthog-segment/blob/main/index.js#L108

**Comment by timgl** [comment]
Fixed in https://github.com/PostHog/posthog-segment/pull/14
